/* Generated By:JJTree: Do not edit this line. ASTJavaCC.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.parser;

public
class ASTJavaCC extends SimpleNode {
  public ASTJavaCC(int id) {
    super(id);
  }

  public ASTJavaCC(HelloParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HelloParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6f1c207311f462897939bdb5829fdf31 (do not edit this line) */
