/* Generated By:JJTree: Do not edit this line. ASTJJTree.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package main.java.parser;

public
class ASTJJTree extends SimpleNode {
  public ASTJJTree(int id) {
    super(id);
  }

  public ASTJJTree(HelloParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(HelloParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4b8b57f30d82356643389b173cf8b596 (do not edit this line) */
