/* Generated By:JavaCC: Do not edit this line. HelloParserDefaultVisitor.java Version 6.1_2 */
package main.java.parser;

public class HelloParserDefaultVisitor implements HelloParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTHello node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTJavaCC node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTJJTree node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=666a1d2e02821d6a098244ce7224b7c5 (do not edit this line) */
