/* Generated By:JavaCC: Do not edit this line. HelloParserVisitor.java Version 6.1_2 */
package main.java.parser;

public interface HelloParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTHello node, Object data);
  public Object visit(ASTJavaCC node, Object data);
  public Object visit(ASTJJTree node, Object data);
}
/* JavaCC - OriginalChecksum=c4548779fec9c6b307fe849f0279fbd8 (do not edit this line) */
