/* Generated By:JavaCC: Do not edit this line. HelloParserTreeConstants.java Version 6.1_2 */
package main.java.parser;

public interface HelloParserTreeConstants
{
  public int JJTHELLO = 0;
  public int JJTVOID = 1;
  public int JJTJAVACC = 2;
  public int JJTJJTREE = 3;


  public String[] jjtNodeName = {
    "Hello",
    "void",
    "JavaCC",
    "JJTree",
  };
}
/* JavaCC - OriginalChecksum=a8fdbb48abb6f8dea078eaa6fb51bed4 (do not edit this line) */
